source('Pi_PlotFunction.R')


# Example for one file (can repeat and change as necessary)
# Input is file: and the mapper for the title of the plot

#Example: Pi_PlotFunction('.pi file generated by popoolation', "additional details for title")

Pi_PlotFunction('F115ConR1_TAGCTT_novo.pi', "Novoalign")

Pi_PlotFunction('F115ConR2_GGCTAC_novo.pi', "Novoalign")

Pi_PlotFunction('F115SelR1_GTTTCG_novo.pi', "Novoalign")

Pi_PlotFunction('F115SelR2_GTGGCC_novo.pi', "Novoalign")

Pi_PlotFunction('F38ConR1_ATCACG_novo.pi', "Novoalign")

Pi_PlotFunction('F38ConR2_TTAGGC_novo.pi', "Novoalign")

Pi_PlotFunction('F38SelR1_ACTTGA_novo.pi', "Novoalign")

Pi_PlotFunction('F38SelR2_GATCAG_novo.pi', "Novoalign")

Pi_PlotFunction('F77ConR1_ATGTCA_novo.pi', "Novoalign")

Pi_PlotFunction('F77ConR2_ATTCCT_novo.pi', "Novoalign")

Pi_PlotFunction('F77SelR1_TTAGGC_novo.pi', "Novoalign")

Pi_PlotFunction('F77SelR2_GATCAG_novo.pi', "Novoalign")

Pi_PlotFunction('MGD3_SO_CAGATC_novo.pi', "Novoalign")






#### IGNORE ######
# Example to run all in a for loop
# Creates a list of all .pi files (from mapper)
MyPi <- list.files(pattern="novo.pi")
MyPi


for (file in MyPi){
  Pi_PlotFunction(file, "Novoalign")
}
